   :PROPERTIES:
   :Time:     23:38
   :END:
I would like to use org-mode and org-journal to keep track of the time worked
for a specific customer. A single journal entry could then register the time
worked for that day, but also for other days.

org-mode stores the clocked work time in a so-called LOGBOOK drawer of a
headline. To give an example, the following LOGBOOK specifies I worked from
9:00 to 17:00 on Tuesday, August 8 2017:
#+BEGIN_EXAMPLE
:LOGBOOK:
CLOCK: [2017-08-08 Tue 22:45]--[2017-08-08 Tue 22:50] =>  0:05
CLOCK: [2017-08-09 Wed 22:45]--[2017-08-09 Wed 22:50] =>  0:05
:END:
#+END_EXAMPLE
As mentioned, I would like to be able to clock more times in the same LOGBOOK.

Using Emacs function org-clock-report you can insert a clocking table with the
total clocking times in a certain time window. Although that function accepts a
lot of parameters to customize its output, I could not use it to create one
table that contained an overview of hours per day.

So I investigated how I could retrieve the required information
programmatically and build the table from that. It was quite a puzzle to find
out how to do that but the following two org-mode functions should make it
possible:
1. org-map-entries, which calls a given function on each headline in your
   agenda files
2. org-clock-sum-current-item, which returns the time clocked on the current
   headline

The following snippet shows how I used this functions to get an initial result:
#+BEGIN_SRC emacs-lisp
(defun my-org-clock-sum-current-item ()
  "Return time, clocked on current item in total."
  (save-excursion
    (save-restriction
      (org-narrow-to-subtree)
      (org-clock-sum (org-matcher-time "2017-08-09") (org-matcher-time "2017-08-10")))))

(org-map-entries 'my-org-clock-sum-current-item "emacs" 'agenda)
#+END_SRC
The last call returns the list of total time clocked on August 9, 2017 for each
headline with tag "emacs".

For now, as a proof-of-concept, this suffices but we are not there yet. For
example, org-clock-report accepts a parameter that allows you to specify the
time window as a specific date, week, month etc. It would be nice if I could
also support this "block" parameter - note that org-clock-get-table-data
contains the code to parse this parameter.
